import { Component } from '@angular/core';

@Component({
  selector: 'app-rail-schedule',
  templateUrl: './rail-schedule.component.html',
  styleUrls: ['./rail-schedule.component.css'],
})
export class RailScheduleComponent {
  inbound: boolean = true;
  outbound: boolean = false;
  filterInbound: any;
  filterOutbound: any;
  outboundDropdown: any;
  inboundDropdown: any;
  inboundData: any;
  outboundData: any;
  ngOnInit() {
    this.inboundData = [
      ...this.data.filter((item) => {
        return item.destination == 'Puri';
      }),
    ];
    this.outboundData = [
      ...this.data.filter((item) => {
        return item.origin == 'Puri';
      }),
    ];
    this.filterInbound = [...this.inboundData];
    this.filterOutbound = [...this.outboundData];
    this.outboundDropdown = [
      ...new Set(this.outboundData.map((item: any) => item.destination)),
    ].sort();
    this.inboundDropdown = [
      ...new Set(this.inboundData.map((item: any) => item.origin)),
    ].sort();
  }
  filterData(val: any) {
    if (this.outbound) {
      if (val.value)
        this.filterOutbound = this.outboundData.filter((data: any) => {
          return data.destination == val.value;
        });
      else this.filterOutbound = [...this.outboundData];
    } else {
      if (val.value)
        this.filterInbound = this.inboundData.filter((data: any) => {
          return data.origin == val.value;
        });
      else this.filterInbound = [...this.inboundData];
    }
  }
  data = [
    {
      trainNo: 8415,
      trainName: 'Jelaswar Puri MEMU Special',
      arrival: '12:30 pm',
      departure: '',
      schedule: 'Tu, Th & Sa',
      origin: 'Jaleswar',
      destination: 'Puri',
    },
    {
      trainNo: 8409,
      trainName: 'Khurda Road Puri MEMU Special',
      arrival: '03:00 pm',
      departure: '',
      schedule: 'Th',
      origin: 'Khurda Road',
      destination: 'Puri',
    },
    {
      trainNo: 8427,
      trainName: 'Angul Puri Fast MEMU Special',
      arrival: '10:30 am',
      departure: '',
      schedule: 'Daily',
      origin: 'Angul',
      destination: 'Puri',
    },
    {
      trainNo: 8424,
      trainName: 'Nuagaon Road Puri Passenger Special',
      arrival: '10:15 am',
      departure: '',
      schedule: 'Daily',
      origin: 'Nuagaon Road',
      destination: 'Puri',
    },
    {
      trainNo: 8431,
      trainName: 'Cuttack - Puri Express MEMU Special',
      arrival: '07:45 pm',
      departure: '',
      schedule: 'Daily',
      origin: 'Cuttack',
      destination: 'Puri',
    },
    {
      trainNo: 8440,
      trainName: 'Patna Puri Special Fare Special',
      arrival: '09:45 am',
      departure: '',
      schedule: 'Mo',
      origin: 'Patna',
      destination: 'Puri',
    },
    {
      trainNo: 2837,
      trainName: 'Santragachi Puri Special Fare Super Fast Special',
      arrival: '04:30 am',
      departure: '',
      schedule: 'Th',
      origin: 'Santragachi',
      destination: 'Puri',
    },
    {
      trainNo: 3101,
      trainName: 'Kolkata Puri Special Fare Summer Special',
      arrival: '09:35 am',
      departure: '',
      schedule: 'Sa',
      origin: 'Kolkata',
      destination: 'Puri',
    },
    {
      trainNo: 8403,
      trainName: 'Khurda Road Puri Passenger Special',
      arrival: '07:20 am',
      departure: '',
      schedule: 'Fr',
      origin: 'Khurda Road',
      destination: 'Puri',
    },
    {
      trainNo: 8011,
      trainName: 'Bhanjpur Puri Special Fare Special',
      arrival: '05:50 am',
      departure: '',
      schedule: 'Fr',
      origin: 'Bhanjpur',
      destination: 'Puri',
    },
    {
      trainNo: 3230,
      trainName: 'Patna Puri Special Fare Special',
      arrival: '02:55 am',
      departure: '',
      schedule: 'Su',
      origin: 'Patna',
      destination: 'Puri',
    },
    {
      trainNo: 12844,
      trainName: 'Ahmedabad Puri Super Fast Express',
      arrival: '08:05 am',
      departure: '',
      schedule: 'Mo, Tu, We & Sa',
      origin: 'Ahmedabad',
      destination: 'Puri',
    },
    {
      trainNo: 20858,
      trainName: 'Sainagar Shirdi Puri Weekly Super Fast Express',
      arrival: '08:50 pm',
      departure: '',
      schedule: 'Mo',
      origin: 'Sainagar Shirdi',
      destination: 'Puri',
    },
    {
      trainNo: 20824,
      trainName: 'Ajmer Puri Super Fast Express',
      arrival: '02:25 pm',
      departure: '',
      schedule: 'Th & Sa',
      origin: 'Ajmer',
      destination: 'Puri',
    },
    {
      trainNo: 20820,
      trainName: 'Okha Puri Dwarka Express',
      arrival: '06:15 pm',
      departure: '',
      schedule: 'Fr',
      origin: 'Okha',
      destination: 'Puri',
    },
    {
      trainNo: 20814,
      trainName: 'Jodhpur Puri Super Fast Express',
      arrival: '10:00 am',
      departure: '',
      schedule: 'Mo',
      origin: 'Jodhpur',
      destination: 'Puri',
    },
    {
      trainNo: 20471,
      trainName: 'Bikaner Puri Super Fast Express',
      arrival: '09:30 am',
      departure: '',
      schedule: 'Tu',
      origin: 'Bikaner',
      destination: 'Puri',
    },
    {
      trainNo: 18478,
      trainName: 'Kalinga Utkal Express',
      arrival: '03:25 am',
      departure: '',
      schedule: 'Daily',
      origin: 'Yog Nagari Rishikesh',
      destination: 'Puri',
    },
    {
      trainNo: 18451,
      trainName: 'Tapaswini Express',
      arrival: '06:10 am',
      departure: '',
      schedule: 'Daily',
      origin: 'Hatia',
      destination: 'Puri',
    },
    {
      trainNo: 18450,
      trainName: 'Baidyanathdham Express',
      arrival: '02:55 am',
      departure: '',
      schedule: 'Th',
      origin: 'Patna',
      destination: 'Puri',
    },
    {
      trainNo: 18426,
      trainName: 'Durg Puri Express',
      arrival: '09:05 am',
      departure: '',
      schedule: 'Daily',
      origin: 'Durg Junction',
      destination: 'Puri',
    },
    {
      trainNo: 20862,
      trainName: 'Ahmedabad Puri Super Fast Express',
      arrival: '06:55 am',
      departure: '',
      schedule: 'Su',
      origin: 'Ahmedabad',
      destination: 'Puri',
    },
    {
      trainNo: 20917,
      trainName: 'Indore Puri Humsafar Express',
      arrival: '06:45 pm',
      departure: '',
      schedule: 'We',
      origin: 'Indore',
      destination: 'Puri',
    },
    {
      trainNo: 22973,
      trainName: 'Gandhidham Puri Weekly Super Fast Express',
      arrival: '08:05 am',
      departure: '',
      schedule: 'Fr',
      origin: 'Gandhidham',
      destination: 'Puri',
    },
    {
      trainNo: 22909,
      trainName: 'Valsad Puri Super Fast Express',
      arrival: '09:30 am',
      departure: '',
      schedule: 'Sa',
      origin: 'Valsad',
      destination: 'Puri',
    },
    {
      trainNo: 22889,
      trainName: 'Samudra Kanya Express',
      arrival: '02:55 am',
      departure: '',
      schedule: 'Mo',
      origin: 'Digha',
      destination: 'Puri',
    },
    {
      trainNo: 22884,
      trainName: 'Yesvantpur Puri Weekly Garib Rath Express',
      arrival: '03:55 am',
      departure: '',
      schedule: 'Mo',
      origin: 'Yesvantpur',
      destination: 'Puri',
    },
    {
      trainNo: 22865,
      trainName: 'Mumbai LTT - Puri Super Fast Express',
      arrival: '08:35 am',
      departure: '',
      schedule: 'Fr',
      origin: 'Lokmanya Tilak Terminus',
      destination: 'Puri',
    },
    {
      trainNo: 22860,
      trainName: 'MGR Chennai Puri Super Fast Express',
      arrival: '01:45 pm',
      departure: '',
      schedule: 'Tu',
      origin: 'Chennai Central',
      destination: 'Puri',
    },
    {
      trainNo: 22835,
      trainName: 'Shalimar Puri Weekly Super Fast Express',
      arrival: '05:10 am',
      departure: '',
      schedule: 'Th',
      origin: 'Shalimar',
      destination: 'Puri',
    },
    {
      trainNo: 22828,
      trainName: 'Surat Puri Weekly Super Fast Express',
      arrival: '02:25 pm',
      departure: '',
      schedule: 'We',
      origin: 'Surat',
      destination: 'Puri',
    },
    {
      trainNo: 22201,
      trainName: 'Sealdah Puri Duronto Express',
      arrival: '03:55 am',
      departure: '',
      schedule: 'Tu, Th & Sa',
      origin: 'Sealdah',
      destination: 'Puri',
    },
    {
      trainNo: 18420,
      trainName: 'Jaynagar Puri Weekly Express',
      arrival: '02:55 am',
      departure: '',
      schedule: 'Su',
      origin: 'Jaynagar',
      destination: 'Puri',
    },
    {
      trainNo: 18418,
      trainName: 'Gunupur - Puri Express',
      arrival: '02:50 pm',
      departure: '',
      schedule: 'Daily',
      origin: 'Gunupur',
      destination: 'Puri',
    },
    {
      trainNo: 12881,
      trainName: 'Shalimar Puri Garib Rath Express',
      arrival: '05:10 am',
      departure: '',
      schedule: 'We & Fr',
      origin: 'Shalimar',
      destination: 'Puri',
    },
    {
      trainNo: 12876,
      trainName: 'Neelachal Express',
      arrival: '06:15 pm',
      departure: '',
      schedule: 'Mo, We & Sa',
      origin: 'Anand Vihar Terminal',
      destination: 'Puri',
    },
    {
      trainNo: 12837,
      trainName: 'Howrah Puri Superfast Express',
      arrival: '07:10 am',
      departure: '',
      schedule: 'Daily',
      origin: 'Howrah',
      destination: 'Puri',
    },
    {
      trainNo: 12821,
      trainName: 'Dhauli Express',
      arrival: '06:00 pm',
      departure: '',
      schedule: 'Daily',
      origin: 'Shalimar',
      destination: 'Puri',
    },
    {
      trainNo: 12816,
      trainName: 'Nandan Kanan Express',
      arrival: '01:15 pm',
      departure: '',
      schedule: 'Su, Tu, Th & Fr',
      origin: 'Anand Vihar Terminal',
      destination: 'Puri',
    },
    {
      trainNo: 12802,
      trainName: 'Purushottam Express',
      arrival: '05:25 am',
      departure: '',
      schedule: 'Daily',
      origin: 'New Delhi',
      destination: 'Puri',
    },
    {
      trainNo: 12277,
      trainName: 'Howrah Puri Shatabdi Express',
      arrival: '09:50 pm',
      departure: '',
      schedule: 'Daily',
      origin: 'Howrah',
      destination: 'Puri',
    },
    {
      trainNo: 12145,
      trainName: 'Mumbai LTT Puri Super Fast Express',
      arrival: '06:55 am',
      departure: '',
      schedule: 'Tu',
      origin: 'Lokmanya Tilak Terminus',
      destination: 'Puri',
    },
    {
      trainNo: 12887,
      trainName: 'Shalimar Puri Weekly Super Fast Express',
      arrival: '05:10 am',
      departure: '',
      schedule: 'Tu',
      origin: 'Shalimar',
      destination: 'Puri',
    },
    {
      trainNo: 12895,
      trainName: 'Shalimar Puri Weekly Super Fast Express',
      arrival: '05:10 am',
      departure: '',
      schedule: 'Sa',
      origin: 'Shalimar',
      destination: 'Puri',
    },
    {
      trainNo: 18415,
      trainName: 'Barbil Puri Express',
      arrival: '08:15 pm',
      departure: '',
      schedule: 'Daily',
      origin: 'Barbil',
      destination: 'Puri',
    },
    {
      trainNo: 18413,
      trainName: 'Paradeep - Puri Intercity Express',
      arrival: '10:10 pm',
      departure: '',
      schedule: 'Daily',
      origin: 'Paradeep',
      destination: 'Puri',
    },
    {
      trainNo: 18409,
      trainName: 'Sri Jagannath Express',
      arrival: '04:30 am',
      departure: '',
      schedule: 'Daily',
      origin: 'Shalimar',
      destination: 'Puri',
    },
    {
      trainNo: 18303,
      trainName: 'Sambalpur Puri Intercity Express',
      arrival: '12:50 pm',
      departure: '',
      schedule: 'Daily',
      origin: 'Sambalpur',
      destination: 'Puri',
    },
    {
      trainNo: 18125,
      trainName: 'Rourkela Puri Intercity Express',
      arrival: '10:55 pm',
      departure: '',
      schedule: 'Daily',
      origin: 'Rourkela',
      destination: 'Puri',
    },
    {
      trainNo: 17480,
      trainName: 'Tirupati Puri Express',
      arrival: '02:35 pm',
      departure: '',
      schedule: 'Su, Tu, We, Th & Sa',
      origin: 'Tirupati',
      destination: 'Puri',
    },
    {
      trainNo: 15644,
      trainName: 'Kamakhya Puri Express',
      arrival: '07:30 am',
      departure: '',
      schedule: 'Sa',
      origin: 'Kamakhya',
      destination: 'Puri',
    },
    {
      trainNo: 15640,
      trainName: 'Kamakhya Puri Express',
      arrival: '02:55 am',
      departure: '',
      schedule: 'Tu',
      origin: 'Kamakhya',
      destination: 'Puri',
    },
    {
      trainNo: 12993,
      trainName: 'Gandhidham Puri Weekly Super Fast Express',
      arrival: '02:25 pm',
      departure: '',
      schedule: 'Su',
      origin: 'Gandhidham',
      destination: 'Puri',
    },
    {
      trainNo: 8413,
      trainName: 'Talcher Puri Passenger Special',
      arrival: '11:15 am',
      departure: '',
      schedule: 'Daily',
      origin: 'Talcher',
      destination: 'Puri',
    },
    {
      trainNo: 22910,
      trainName: 'Puri Valsad Super Fast Express',
      arrival: '',
      departure: '12:30 am',
      schedule: 'Su',
      origin: 'Puri',
      destination: 'Valsad',
    },
    {
      trainNo: 20918,
      trainName: 'Puri Indore Humsafar Express',
      arrival: '',
      departure: '12:30 am',
      schedule: 'Th',
      origin: 'Puri',
      destination: 'Indore',
    },
    {
      trainNo: 18126,
      trainName: 'Puri Rourkela Intercity Express',
      arrival: '',
      departure: '04:35 am',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Rourkela',
    },
    {
      trainNo: 12278,
      trainName: 'Puri Howrah Shatabdi Express',
      arrival: '',
      departure: '05:45 am',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Howrah',
    },
    {
      trainNo: 22866,
      trainName: 'Puri Mumbai LTT Super Fast Express',
      arrival: '',
      departure: '06:00 am',
      schedule: 'Tu',
      origin: 'Puri',
      destination: 'Lokmanya Tilak Terminus',
    },
    {
      trainNo: 18414,
      trainName: 'Puri - Paradeep Intercity Express',
      arrival: '',
      departure: '06:15 am',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Paradeep',
    },
    {
      trainNo: 18416,
      trainName: 'Puri Barbil Express',
      arrival: '',
      departure: '06:15 am',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Barbil',
    },
    {
      trainNo: 20472,
      trainName: 'Puri Bikaner Super Fast Express',
      arrival: '',
      departure: '06:35 am',
      schedule: 'We',
      origin: 'Puri',
      destination: 'Bikaner',
    },
    {
      trainNo: 8432,
      trainName: 'Puri Cuttack MEMU Special',
      arrival: '',
      departure: '08:00 am',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Cuttack',
    },
    {
      trainNo: 20819,
      trainName: 'Puri Okha Dwarka Express',
      arrival: '',
      departure: '09:50 am',
      schedule: 'Su',
      origin: 'Puri',
      destination: 'Okha',
    },
    {
      trainNo: 12822,
      trainName: 'Dhauli Express',
      arrival: '',
      departure: '10:25 am',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Shalimar',
    },
    {
      trainNo: 12875,
      trainName: 'Neelachal Express',
      arrival: '',
      departure: '11:00 am',
      schedule: 'Su, Tu & Fr',
      origin: 'Puri',
      destination: 'Anand Vihar Terminal',
    },
    {
      trainNo: 12815,
      trainName: 'Nandan Kanan Express',
      arrival: '',
      departure: '11:00 am',
      schedule: 'Mo, We, Th & Sa',
      origin: 'Puri',
      destination: 'Anand Vihar Terminal',
    },
    {
      trainNo: 22974,
      trainName: 'Puri Gandhidham Weekly Super Fast Express',
      arrival: '',
      departure: '11:15 am',
      schedule: 'Sa',
      origin: 'Puri',
      destination: 'Gandhidham',
    },
    {
      trainNo: 8410,
      trainName: 'Puri Khurda Road MEMU Special',
      arrival: '',
      departure: '11:25 am',
      schedule: 'We',
      origin: 'Puri',
      destination: 'Khurda Road',
    },
    {
      trainNo: 18417,
      trainName: 'Puri - Gunupur Express',
      arrival: '',
      departure: '12:20 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Gunupur',
    },
    {
      trainNo: 8416,
      trainName: 'Puri Jaleswar MEMU Special',
      arrival: '',
      departure: '01:15 pm',
      schedule: 'Mo, We & Fr',
      origin: 'Puri',
      destination: 'Jaleswar',
    },
    {
      trainNo: 8439,
      trainName: 'Puri Patna Special Fare Special',
      arrival: '',
      departure: '02:55 pm',
      schedule: 'Sa',
      origin: 'Puri',
      destination: 'Patna',
    },
    {
      trainNo: 15639,
      trainName: 'Puri Kamakhya Express',
      arrival: '',
      departure: '02:55 pm',
      schedule: 'Tu',
      origin: 'Puri',
      destination: 'Kamakhya',
    },
    {
      trainNo: 18419,
      trainName: 'Puri Jaynagar Weekly Express',
      arrival: '',
      departure: '02:55 pm',
      schedule: 'Th',
      origin: 'Puri',
      destination: 'Jaynagar',
    },
    {
      trainNo: 18449,
      trainName: 'Baidyanathdham Express',
      arrival: '',
      departure: '02:55 pm',
      schedule: 'Mo',
      origin: 'Puri',
      destination: 'Patna',
    },
    {
      trainNo: 3229,
      trainName: 'Puri Patna Special Fare Special',
      arrival: '',
      departure: '02:55 pm',
      schedule: 'Mo',
      origin: 'Puri',
      destination: 'Patna',
    },
    {
      trainNo: 22883,
      trainName: 'Puri Yesvantpur Weekly Garib Rath Express',
      arrival: '',
      departure: '03:15 pm',
      schedule: 'Fr',
      origin: 'Puri',
      destination: 'Yesvantpur',
    },
    {
      trainNo: 3102,
      trainName: 'Puri Kolkata Special Fare Summer Special',
      arrival: '',
      departure: '03:50 pm',
      schedule: 'Sa',
      origin: 'Puri',
      destination: 'Kolkata',
    },
    {
      trainNo: 20813,
      trainName: 'Puri Jodhpur Super Fast Express',
      arrival: '',
      departure: '03:50 pm',
      schedule: 'We',
      origin: 'Puri',
      destination: 'Jodhpur',
    },
    {
      trainNo: 18304,
      trainName: 'Puri Sambalpur Intercity Express',
      arrival: '',
      departure: '04:05 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Sambalpur',
    },
    {
      trainNo: 8428,
      trainName: 'Puri Angul Fast MEMU Special',
      arrival: '',
      departure: '05:00 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Angul',
    },
    {
      trainNo: 8414,
      trainName: 'Puri Talcher Passenger Special',
      arrival: '',
      departure: '05:15 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Talcher',
    },
    {
      trainNo: 22859,
      trainName: 'Puri MGR Chennai Super Fast Express',
      arrival: '',
      departure: '05:30 pm',
      schedule: 'Su',
      origin: 'Puri',
      destination: 'Chennai Central',
    },
    {
      trainNo: 12843,
      trainName: 'Puri Ahmedabad Super Fast Express',
      arrival: '',
      departure: '05:30 pm',
      schedule: 'Tu, Th, Fr & Sa',
      origin: 'Puri',
      destination: 'Ahmedabad',
    },
    {
      trainNo: 8423,
      trainName: 'Puri Nuagaon Road Passenger Special',
      arrival: '',
      departure: '06:00 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Nuagaon Road',
    },
    {
      trainNo: 17479,
      trainName: 'Puri Tirupati Express',
      arrival: '',
      departure: '06:30 pm',
      schedule: 'Su, Mo, We, Th & Fr',
      origin: 'Puri',
      destination: 'Tirupati',
    },
    {
      trainNo: 18425,
      trainName: 'Puri Durg Express',
      arrival: '',
      departure: '07:10 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Durg Junction',
    },
    {
      trainNo: 2838,
      trainName: 'Puri Santragachi Special Fare Super Fast Special',
      arrival: '',
      departure: '07:20 pm',
      schedule: 'Fr',
      origin: 'Puri',
      destination: 'Santragachi',
    },
    {
      trainNo: 20861,
      trainName: 'Puri Ahmedabad Super Fast Express',
      arrival: '',
      departure: '07:25 pm',
      schedule: 'We',
      origin: 'Puri',
      destination: 'Ahmedabad',
    },
    {
      trainNo: 22202,
      trainName: 'Puri Sealdah Duronto Express',
      arrival: '',
      departure: '07:25 pm',
      schedule: 'Tu, Th & Sa',
      origin: 'Puri',
      destination: 'Sealdah',
    },
    {
      trainNo: 12994,
      trainName: 'Puri Gandhidham Weekly Super Fast Express',
      arrival: '',
      departure: '08:00 pm',
      schedule: 'Mo',
      origin: 'Puri',
      destination: 'Gandhidham',
    },
    {
      trainNo: 22827,
      trainName: 'Puri Surat Weekly Super Fast Express',
      arrival: '',
      departure: '08:00 pm',
      schedule: 'Su',
      origin: 'Puri',
      destination: 'Surat',
    },
    {
      trainNo: 12838,
      trainName: 'Puri Howrah Superfast Express',
      arrival: '',
      departure: '08:15 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Howrah',
    },
    {
      trainNo: 18452,
      trainName: 'Tapaswini Express',
      arrival: '',
      departure: '08:30 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Hatia',
    },
    {
      trainNo: 18477,
      trainName: 'Kalinga Utkal Express',
      arrival: '',
      departure: '08:45 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Yog Nagari Rishikesh',
    },
    {
      trainNo: 22890,
      trainName: 'Samudra Kanya Express',
      arrival: '',
      departure: '09:05 pm',
      schedule: 'Sa',
      origin: 'Puri',
      destination: 'Digha',
    },
    {
      trainNo: 12146,
      trainName: 'Puri Mumbai LTT Super Fast Express',
      arrival: '',
      departure: '09:40 pm',
      schedule: 'Tu',
      origin: 'Puri',
      destination: 'Lokmanya Tilak Terminus',
    },
    {
      trainNo: 12801,
      trainName: 'Purushottam Express',
      arrival: '',
      departure: '09:55 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'New Delhi',
    },
    {
      trainNo: 12888,
      trainName: 'Puri Shalimar Weekly Super Fast Express',
      arrival: '',
      departure: '10:10 pm',
      schedule: 'Su',
      origin: 'Puri',
      destination: 'Shalimar',
    },
    {
      trainNo: 15643,
      trainName: 'Puri Kamakhya Express',
      arrival: '',
      departure: '10:10 pm',
      schedule: 'Sa',
      origin: 'Puri',
      destination: 'Kamakhya',
    },
    {
      trainNo: 22836,
      trainName: 'Puri Shalimar Weekly Super Fast Express',
      arrival: '',
      departure: '10:10 pm',
      schedule: 'Tu',
      origin: 'Puri',
      destination: 'Shalimar',
    },
    {
      trainNo: 12882,
      trainName: 'Puri Shalimar Garib Rath Express',
      arrival: '',
      departure: '10:10 pm',
      schedule: 'Mo & We',
      origin: 'Puri',
      destination: 'Shalimar',
    },
    {
      trainNo: 12896,
      trainName: 'Puri Shalimar Weekly Super Fast Express',
      arrival: '',
      departure: '10:10 pm',
      schedule: 'Th',
      origin: 'Puri',
      destination: 'Shalimar',
    },
    {
      trainNo: 18410,
      trainName: 'Sri Jagannath Express',
      arrival: '',
      departure: '10:40 pm',
      schedule: 'Daily',
      origin: 'Puri',
      destination: 'Shalimar',
    },
    {
      trainNo: 20823,
      trainName: 'Puri Ajmer Super Fast Express',
      arrival: '',
      departure: '11:05 pm',
      schedule: 'Mo & Th',
      origin: 'Puri',
      destination: 'Ajmer',
    },
    {
      trainNo: 20857,
      trainName: 'Puri Sainagar Shirdi Weekly Super Fast Express',
      arrival: '',
      departure: '11:05 pm',
      schedule: 'Fr',
      origin: 'Puri',
      destination: 'Sainagar Shirdi',
    },
    {
      trainNo: 8404,
      trainName: 'Puri Khurda Road Passenger Special',
      arrival: '',
      departure: '11:10 pm',
      schedule: 'Sa',
      origin: 'Puri',
      destination: 'Khurda Road',
    },
    {
      trainNo: 8012,
      trainName: 'Puri Bhanjpur Special Fare Special',
      arrival: '',
      departure: '11:50 pm',
      schedule: 'Fr',
      origin: 'Puri',
      destination: 'Bhanjpur',
    },
  ];
}
